#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: homelab

networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - TZ=America/Bogota
    labels:
      - com.centurylinklabs.watchtower.enable=true

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - SIGNUPS_ALLOWED=false
    restart: unless-stopped
    volumes:
      - /data/docker/vw-data/:/data/
    ports:
      - 8082:80

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=${TZ}
      - WEBUI_PORT=8069 # must match "qbittorrent web interface" port number in gluetun's service above
    ports:
      - 8069:8069
    volumes:
      - /data/docker/qbittorrent:/config
      - /data:/data
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.6
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "qbittorrent"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=${TZ}
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/prowlarr:/config
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.2
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "prowlarr"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.3
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "sonarr"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.4
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "radarr"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/bazarr:/config
      - /data:/data
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.7
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "bazarr"

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.8
    